INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи часто ви відчуваєте потяг до нових вражень, щоб випробувати сильні відчуття?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи часто Ви відчуваєте, що маєте потребу в друзях, які можуть Вас зрозуміти, підбадьорити, поспівчувати?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи вважаєте Ви себе безтурботною людиною?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи правда, що Вам дуже важко відповідати "ні"?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Обмірковуєте Ви свої справи не поспішаючи і вважаєте за краще почекати, перш ніж діяти?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи завжди Ви стримуєте свої обіцянки, навіть якщо Вам це не вигідно?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи часто у вас бувають спади і підйоми настрою?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи швидко Ви зазвичай дієте і говорите, і не розтрачуєте чи багато часу на обдумування?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи виникало у Вас коли-небудь почуття, що Ви нещасні, хоча ніякої серйозної причини для цього не було?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи правда, що на спір Ви здатні зважитися на все?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'бентежить Ви, коли хочете познайомитися з людиною протилежної статі, який Вам симпатичний?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи буває, що, розсердившись, Ви виходите з себе?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи часто Ви дієте під впливом хвилинного настрою?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи часто Вас турбують думки про те, що Вам не варто було чогось робити або говорити?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи вважаєте Ви читання книг зустрічам з людьми?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Вас легко образити?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи любите Ви часто бувати в компанії?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи бувають у Вас іноді такі думки, які Ви хотіли б приховати від інших людей?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи правда, що іноді Ви настільки сповнені енергії, що все горить в руках, а іноді відчуваєте сильну млявість?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи вважаєте Ви мати друзів поменше, але особливо близьких Вам?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи часто Ви мрієте?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Коли на Вас кричать, Ви відповідаєте тим же?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи часто Вас турбує почуття провини?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи всі ваші звички хороші і бажані?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи здатні ви дати волю власним почуттям і щосили повеселитися в галасливій компанії?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи вважаєте Ви себе людиною збудливим і чутливим?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи вважають Вас людиною живим і веселим?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Після того, як справу зроблено, чи часто Ви повертаєтеся до нього подумки і думає, що могли б зробити краще?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Ви зазвичай мовчазний і стриманий, коли перебуваєте серед людей?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Ви іноді брешете?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи буває, що Вам не спиться через те, що різні думки лізуть в голову?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи вірно, що Вам приємніше і легше прочитати про те, що Вас цікавить в книзі, хоча можна швидше і простіше дізнатися про це у друзів?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи буває у Вас сильне серцебиття?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи подобається Вам робота, що вимагає постійної уваги?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи буває, що Вас "кидає в тремтіння"?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи вірно, що Ви завжди говорите про знайомих Вам людей тільки хороше, навіть тоді, коли впевнені, що вони про це не дізнаються?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи правда, що Вам не приємно бувати в компанії, де постійно жартують один над одним?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Ви дратівливі?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи подобається Вам робота, яка вимагає швидкості дій?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи вірно, що Вас не рідко не дають спокою думки про різні неприємності і "жахи", які могли б статися, хоча все скінчилося благополучно?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Ви ходите повільно і неквапливо?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Ви коли-небудь спізнювалися на побачення, роботу або навчання?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи часто Вам сняться кошмари?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи правда, що Ви такий любитель поговорити, що ніколи не пропустіть зручного випадку поговорити з незнайомою людиною?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи турбують Вас які-небудь болі?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Засмутилися б Ви, якби довго не могли бачитися зі своїми друзями?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи можете Ви назвати себе нервовою людиною?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи є серед Ваших знайомих такі, які Вам явно не подобаються?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи можете Ви сказати, що Ви впевнена в собі людина?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи легко Вас зачіпає критика Ваших недоліків або Вашої роботи?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи важко отримати справжнє задоволення від вечірки?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи турбує Вас почуття, що Ви чимось гірші за інших?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи зуміли б Ви внести пожвавлення в нудну компанію?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи буває, що Ви говорите про речі, в яких зовсім не розумієтеся?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Стурбовані Ви про своє здоровя?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи любите Ви пожартувати над іншими?', 'Так,Ні' )
INSERT INTO Questions VALUES( 'UK', 'Temperament', 'Чи страждаєте Ви від безсоння?', 'Так,Ні' )
